name: coverage workflow
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  coverage-workflow:
    name: "Label PR when run test"
    runs-on: ubuntu-latest
    steps:
      - name: "Do nothing. Only trigger corresponding workflow_run event"
        run: echo
